### ISSUE TITLE
How do I host this on windows?

### ISSUE THREAD

**Issue by ghost** [achimala/leaguelib#17]
I am a complete newbie in this but I need somekind of loldata because im developing mobile application. Currently im using elophant api which is unstable. Can you please explain me how to get this working?

**Comment by timlinde** [comment]
I think it would be easier for you to use an existing API here:

https://www.mashape.com/search?query=League+of+legends

Since it will take allot of time for you to keep an api up yourself.

Please also note that this code is just like the Client you use in League of Legends. If Riots servers have problems, you wont get any data. And on every update you have to change versionNumbers recompile your source and so on.

If you dont know how to run it on Windows you probably shouldn't.

**Comment by ghost** [comment]
Thank you for your quick response, will test it out.
