### ISSUE TITLE
making web based api

### ISSUE THREAD

**Issue by doctorrapido** [achimala/leaguelib#18]
Hey. I am bad at java and need some api like that for my website . I use too much api ( based js, php ...).This script is good and well developed. 

I wanna use that script with 
http : //............../:region/active/:internalName
http : //............../:region/summoner/:summonername

is that possible ? 

I tried to edit your java files but I cant do more things cause of bad at java.
(I can run your maintest.java and getting info from to console.But I have no idea how can I extract to webpage )
sorry for my ignorance :)

**Comment by Nano-GG** [comment]
You are just like me, i'm very good PHP developer, and i want start making a lol site for my community, but stuck on java, so until no more detailed information or non-experts java developer guide, my project is die

:(

**Comment by timlinde** [comment]
https://www.mashape.com/search?query=League+of+legends

Use this instead.

**Comment by doctorrapido** [comment]
I want to host script on my server.Your script what is linked is so slow. I used that before

**Comment by tyrust** [comment]
How much would you be willing to pay for a responsive API? We (at lolteam.net) could provide an API, but we would need money for infrastructure and incentive to do so (since we are busy with school and jobs of our own).

**Comment by Nano-GG** [comment]
@timlinde whats the point for use that services for code-learn project?, none of them are free source code, some of them need you to pay.

**Comment by doctorrapido** [comment]
I have server for it and i guess everybody has server for project or website . So i dont want to get information from another website or source that must be local for speed. (getting info from mashape takes 8-14 sec) . i can donate (u can say how much is enough)if u can write script like that (not api service to consumers) . Just script not full service :) 
Sorry if i didnt be clear and i dont know coding for it is so hard or easy :) i have really no idea on java
U can check lolpro and lolfire at github

**Comment by Nano-GG** [comment]
Yes, because each developer has his own way, at least i'm not requesting an API, i'm requesting a little guide for start coding an PHP site using this library, or one script wich can be the start of my own project. and I'm willing to pay for that knowledge.

I dont want to use the service or API by a third person, wich you cannot improve, cannot modify, would be great just an API or documentation on how we can use this library on custom projects for non-experts java developers.

**Comment by tyrust** [comment]
@doctorrapido Well now I am confused. When you opened this issue you said you wanted HTTP endpoints, but now you're saying you want to get the information "locally". You can use LeagueLib as it exists right now to do that. The reason why LeagueLib is in Java is because it uses an [already existing RTMPS library](https://code.google.com/p/lolrtmpsclient/) that is written in Java. If you would like to implement something in another language, you will have to build it up on your own.

@n4ndo I'm sorry to say that we don't really have plans for any more documentation_. The code is fairly straightforward for those that are familiar with Java. So if you want to use this Java library, you should probably learn how to use Java.
\_ - I guess you did say that you are willing to pay. If that is really the case please provide contact info and we can perhaps discuss something

**Comment by timlinde** [comment]
@n4ndo Maybe you should make a more simple project in java then? I mean to make this source work, you need to use Sockets, threading etc. So i suggest you read up on java first before getting into how to make this run on your own project. It is absolutely not just clone and run. You will have to code your own file to get the data your own way.

Hope this was explained good enough.

**Comment by doctorrapido** [comment]
So I will try to learn java and searching ways for integrate to php. Thanks for your Replies

**Comment by genesisdk** [comment]
tyrust  ive  already tried  communicating with anshu not   really an answear,  tho   , and ur contact info isnt really here.   except ur   na account and im an euw  account.

 but i would like to have  have this  api runing   on my own . i  told anshu i  would like to talk about   costs of u guys setting it up . so  if u have some  contact info  and  we can  talk about  it ?

**Comment by tyrust** [comment]
I've added contact info to my github profile. Feel free to email me about this, @genesisdk and @n4ndo.

It seems like this discussion has reached a natural end, so I will close this issue.
