### ISSUE TITLE
NullPointerException on null seasonOneTier field on a fillPublicSummonerData

### ISSUE THREAD

**Issue by Jarlenai** [achimala/leaguelib#6]
In LeagueSummonerProfileInfo.java:29,  you call valueOf on the LeagueRankedTier enum. If the player's seasonOneTier field is null, this results in a NullPointerException. I've currently only found one player this occurs for:

```
com.riotgames.platform.summoner.BasePublicSummonerDTO:{seasonTwoTier=UNRANKED, internalName=zekenttime, acctId=2.08282908E8, seasonOneTier=null, name=Zekent Time, profileIconId=23, sumId=4.4979321E7}
```

Personally, I don't know what it means, I'm not sure if he was unranked in season one or if the server simply does not know. 

To fix it in my code I added the following to LeagueRankedTier:

``` java
public static LeagueRankedTier getTier(String tier) {
        for(LeagueRankedTier tierEnum : LeagueRankedTier.values())
            if(tierEnum.name().equalsIgnoreCase(tier))
                return tierEnum;
        return null;
    }
```

Then just called that instead of valueOf.

**Comment by tyrust** [comment]
Riot used to send only the Season 2 Tier, which is why Season 1 Tier ended up being null. In 3.13 they changed it so now they only send the "last season" tier. Support for this was added in commit 8706d22269928019d19ed4a044d44bba308d47a3. Now when we call 

```
_previousSeasonHighestTier = LeagueRankedTier.valueOf(obj.getString("previousSeasonHighestTier"));
```

I think that we can be sure that previousSeasonHighestTier will be a non-null and valid value.
